# Generated by Django 5.2 on 2025-04-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_follow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='bg_pic',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='signup',
            name='profile_pic',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
