# Generated by Django 5.2 on 2025-04-25 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
